CREATE TABLE IF NOT EXISTS movie_service.tickets (
    id BIGSERIAL PRIMARY KEY,
    movie_name VARCHAR(50) NOT NULL,
    showtime TIMESTAMP WITH TIME ZONE NOT NULL,
    genre TEXT CHECK (genre IN ('ACTION', 'COMEDY', 'DRAMA', 'HORROR', 'SCIFI', 'ROMANCE', 'THRILLER')),
    seat VARCHAR(5) NOT NULL,
    ticket_id VARCHAR(7) NOT NULL,
    time_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);